blueprint:
  name: Bambu Lab WLED Controller
  description: Control one or more WLED lights with Bambu 3d printer
  domain: automation
  input:
    printer_status:
      name: Print Status of your Bambu Lab printer
      description: Select the print status entity.
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: bambu_lab
          multiple: false
    printer_stage:
      name: Current Stage of your Bambu Lab Printer
      description: Select the printer current stage entity.
      selector:
        entity:
          filter:
          - domain:
            - sensor
            integration: bambu_lab
          multiple: false
    printer_state:
      name: Printer state On/Off of your Bambu Lab Printer
      description: Select the printer state binary sensor.
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
            integration: bambu_lab
          multiple: false
    chamber_light:
      name: Chamber Light of your Bambu Lab Printer
      description: "Select the printer chamber light entity."
      selector:
        entity:
          filter:
            domain: light
            integration: bambu_lab
    wled_lights:
      name: WLED Light devices
      description: Select the WLED light devices you wish to control.
      selector:
        device:
          filter:
          - integration: wled
          multiple: true
alias: Bambu Lab WLED Controller
description: ''
trigger:
- platform: state
  entity_id:
  - !input chamber_light
  - !input printer_state
  - !input printer_status
  - !input printer_stage
  alias: When printer stage,status or state changes
condition: []
action:
- delay:
    hours: 0
    minutes: 0
    seconds: 5
    milliseconds: 0
- if:
  - condition: state
    state: 'on'
    alias: printer state is on
    entity_id: !input printer_state
  - condition: not
    conditions:
    - condition: state
      entity_id: !input printer_stage
      state: scanning_bed_surface
      alias: scanning Bed Surface
    - condition: state
      entity_id: !input printer_stage
      state: cleaning_nozzle_tip
      alias: cleaning Nozzle Tip
    - condition: state
      entity_id: !input printer_stage
      state: calibrating_extrusion
      alias: Calibrating extrusion
    - condition: state
      entity_id: !input printer_stage
      state: calibrating_micro_lidar
      alias: Calibrating micro lidar
    - condition: state
      entity_id: !input printer_status
      state: offline
      alias: Printer is off
    alias: And Lidar is NOT on
  then:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 255
      - 255
      brightness_pct: 100
      effect: Freqmatrix
    alias: Turn WLED light on white with effect
    target:
      device_id: !input wled_lights
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: paused_filament_runout
        - condition: state
          entity_id: !input printer_stage
          state: paused_front_cover_falling
        - condition: state
          entity_id: !input printer_stage
          state: paused_nozzle_temperature_malfunction
        - condition: state
          entity_id: !input printer_stage
          state: paused_heat_bed_temperature_malfunction
        - condition: state
          entity_id: !input printer_stage
          state: paused_chamber_temperature_control_error
        - condition: state
          entity_id: !input printer_stage
          state: paused_cutter_error
        - condition: state
          entity_id: !input printer_stage
          state: paused_first_layer_error
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness: 255
          effect: Blink
        target:
          device_id: !input wled_lights
        alias: Turn on Wled to red
    alias: Do we need to set color to red?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: idle
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 0
          - 195
          brightness: 200
          effect: Oscillate
        target:
          device_id: !input wled_lights
        alias: Turn on Wled to fushia with oscillate effect
    alias: Do we need to set color to white?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: filament_unloading
        - condition: state
          entity_id: !input printer_stage
          state: filament_loading        
        - condition: state
          entity_id: !input chamber_light
          state: "on"        
        - condition: state
          entity_id: !input printer_stage
          state: printing
      sequence:
      - service: light.turn_on
        data:
          rgbw_color:
            - 0
            - 0
            - 0
            - 255
          brightness: 255
          effect: Solid
        target:
          device_id: !input wled_lights
        alias: Turn on Wled to full white while printing
    alias: Do we need to set color to white?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_status
          state: finish
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 0
          - 255
          - 0
          brightness: 255
          effect: Solid
        target:
          device_id: !input wled_lights
        alias: Turn on Wled to green
    alias: Do we need to set color to green?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_status
          state: pause
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 0
          - 255
          - 0
          brightness: 255
          effect: Blink
        target:
          device_id: !input wled_lights
        alias: Turn on Wled to green with blink effect
    alias: Do we need to set color to green?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: auto_bed_leveling
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 0
          - 0
          - 255
          brightness: 255
          effect: Blink
        target:
          device_id: !input wled_lights
        alias: Turn on Wled to blue
    alias: Do we need to set color to blue?
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: !input printer_stage
          state: heatbed_preheating
        - condition: state
          entity_id: !input printer_stage
          state: Heating Hotend
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 169
          - 0
          brightness: 255
          effect: Blink
        target:
          device_id: !input wled_lights
        alias: Turn on Wled to yellow
    alias: Do we need to set color to yellow?
  - choose:
      - conditions:
        - condition: or
          conditions:
          - condition: state
            state: "off"
            alias: printer state is off
            entity_id: !input printer_state
          - condition: state
            entity_id: !input chamber_light
            state: "off"
            alias: chamber light is off
          - condition: state
            entity_id: !input printer_stage
            state: calibrating_extrusion
            alias: Calibrating extrusion
          - condition: state
            entity_id: !input printer_stage
            state: calibrating_micro_lidar
            alias: Calibrating micro lidar                       
      sequence:
        - service: light.turn_off
          data: {}
          target:
            device_id: !input wled_lights
    alias: Do we need to turn off the lights?    
mode: single
